name: dx-env
channels:
- bioconda
- r
- conda-forge
- defaults
dependencies:
- dxpy=0.225.0=py27_0
- fusepy=2.0.4=py27_0
- libmagic=5.25=0
- python-dateutil=2.3=py27_0
- python-magic=0.4.12=py27_0
- asn1crypto=0.22.0=py27_0
- beautifulsoup4=4.6.0=py27_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py27_0
- cffi=1.10.0=py27_0
- chardet=3.0.4=py27_0
- cryptography=2.0.3=py27_0
- enum34=1.1.6=py27_1
- futures=3.0.5=py27_0
- idna=2.6=py_0
- ipaddress=1.0.18=py27_0
- libffi=3.2.1=3
- ncurses=5.9=10
- openssl=1.0.2l=0
- pip=9.0.1=py27_0
- psutil=5.2.2=py27_0
- pycparser=2.18=py27_0
- pyopenssl=17.2.0=py27_0
- pysocks=1.6.7=py27_0
- python=2.7.13=1
- readline=6.2=0
- requests=2.18.4=py27_1
- requestsexceptions=1.3.0=py27_0
- setuptools=36.3.0=py27_0
- six=1.11.0=py27_1
- sqlite=3.13.0=1
- tk=8.5.19=2
- urllib3=1.22=py27_0
- wheel=0.30.0=py_1
- ws4py=0.4.2=py27_0
- xattr=0.9.2=py27_0
- zlib=1.2.11=0
